# Generated by Django 5.1.3 on 2024-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('consumption_twh', models.FloatField()),
            ],
        ),
    ]
